---
- import_tasks: ecr/podman-ecr-login.yml

- name: create nginx fulfillr-site directory
  become: true
  ansible.builtin.file:
    path: /usr/local/share/fulfillr-site
    state: directory
    owner: "fedora"
    group: "wheel"
    mode: 0755

- name: create fulfillr host directory volumes
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0755
  notify: restorecon podman
  loop:
    - "{{ fulfillr_path }}"

- name: template fulfillr config
  become: true
  ansible.builtin.template:
    src: "templates/fulfillr/{{ item }}.j2"
    dest: "{{ fulfillr_path }}/{{ item }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0644
  loop:
    - production.json
  notify:
    - restorecon podman

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- import_tasks: podman/podman-check.yml
  vars:
    container_name: fulfillr
    container_image: "{{ image }}"

- name: create fulfillr server container
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_container:
    name: fulfillr
    image: "{{ image }}"
    image_strict: true
    command: --config /config/production.json
    restart_policy: on-failure:3
    log_driver: journald
    volumes:
      - "{{ fulfillr_path }}:/config"
    ports:
      - 9054:8080/tcp

- name: create systemd startup job for fulfillr
  include_tasks: podman/systemd-generate.yml
  vars:
    container_name: fulfillr
