---
- name: create motion directory
  become: true
  file:
    path: "{{ motion_target_dir }}"
    state: directory
    owner: "{{ nfs_user }}"
    group: "{{ nfs_group }}"
    mode: 0755

- name: template motion config
  become: true
  template:
    src: templates/motion.conf.j2
    dest: /etc/motion/motion.conf
    mode: 0644
    backup: true
  notify:
    - restart_motion

- name: enable (now) motion.service
  become: true
  service:
    name: motion.service
    state: started
    enabled: true
