---
- name: renew certbot ssl certificates weekly
  become: true
  cron:
    name: certbot_renew
    special_time: weekly
    job: |
      certbot renew --pre-hook "systemctl stop nginx" \
       --post-hook "systemctl start nginx"
  tags: cron
