---
- name: set http/https firewall rules
  become: true
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - http
    - https
  notify: restart firewalld
  tags: firewall
