---
- name: create home-assistant host directory volumes
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0640
  with_items:
    - /usr/share/hass
    - /usr/share/hass/media
    - /var/lib/private/hass
  tags: hass

- name: copy configuration and automations
  become: true
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/var/lib/private/hass/{{ item }}"
    mode: 0644
  with_items:
    - configuration.yaml
    - automations.yaml
  tags: hass

- name: create home-assistant server container
  diff: false
  community.general.docker_container:
    name: hass
    image: ghcr.io/home-assistant/home-assistant:stable
    recreate: false
    restart: true
    restart_policy: on-failure
    restart_retries: 3
    log_driver: syslog
    log_options:
      syslog-address: "udp://localhost:{{ syslog_udp_default }}"
      syslog-facility: daemon
      tag: "docker/{{'{{'}}.Name{{'}}'}}"
    volumes:
      - /var/lib/hass:/config
      - /usr/share/hass:/share
    ports:
      - "8123:8123"
  tags: hass
