kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
  - name: lint
    image: bdebyl/yamllint
    command:
      - export YML_FILES="$(find ansible/ -name '*.yml' -not -name '*vault*')"
      - . .lint-vars.sh
      - ansible-lint -x "$ANSIBLE_LINT_SKIP_LIST" "$YML_FILES"
      - yamllint "$YML_FILES"
