---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: docker.io/bdebyl/yamllint:1.0.88
    pull: always
    commands:
      - yamllint ansible/

trigger:
  event:
    exclude:
    - pull_request
---
kind: signature
hmac: 92b44bfb500ce873eb00d47a1c0c317bdad75374081f5fe34d8c35031dd685e6

...
