---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: docker.io/bdebyl/yamllint:1.0.88
    pull: always
    commands:
      - yamllint -c .yamllint.yml --list-files ansible/

trigger:
  event:
    exclude:
    - pull_request
---
kind: signature
hmac: a46331cb776bdedaf3584f833730a81fe16cf429880fe3480f8a4412247cf006

...
