kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
  - name: lint
    image: cytopia/ansible-lint
    command:
      - export YML_FILES="$(find ansible/ -name '*.yml' -not -name '*vault*')"
      - ansible-lint -x 701 "$YML_FILES"
      - yamllint "$YML_FILES"
