---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: bdebyl/yamllint
    pull: always
    command:
      - make lint-ci

trigger:
  event:
    exclude:
    - pull_request
---
kind: signature
hmac: 12a8371679582716620cf0d32554684aabb0e86bdda3c849eca3e9dc55738b84

...
