---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: bdebyl/yamllint
    command:
      - make lint-ci

trigger:
  event:
    exclude:
    - pull_request
---
kind: signature
hmac: 7e505a3615347898a4858753d4bcc19295548c84278e48eb68cfff38dfe1eed6

...
