---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: docker.io/bdebyl/yamllint:1.0.87
    pull: always
    command: ansible/

trigger:
  event:
    exclude:
    - pull_request
---
kind: signature
hmac: 082ae2026ee2c326e1b088e1ee9739af23a3fdf3585dd9bc3fc5c033084be840

...
