---
- name: renew certbot ssl certificates weekly
  become: true
  cron:
    name: certbot_renew
    special_time: weekly
    job: >-
      certbot renew --post-hook 'systemctl restart nginx'
  tags: cron
