---
- name: ensure desired services are started and enabled
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ services }}"
  tags: security, service
