---
- name: restart_sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: restart_fail2ban
  become: true
  ansible.builtin.service:
    name: fail2ban
    state: restarted
