---
deps:
  [
    cockpit-podman,
    cronie,
    fail2ban,
    fail2ban-selinux,
    git,
    logrotate,
    podman,
    podman-docker,
    python-docker,
  ]

fail2ban_jails: [sshd.local]

services:
  - crond
  - podman.socket
  - podman
  - fail2ban
  - systemd-timesyncd
