---
deps:
  [
    cockpit-podman,
    cronie,
    docker,
    fail2ban,
    fail2ban-selinux,
    git,
    logrotate,
    podman,
    python-docker,
  ]

fail2ban_jails: [sshd.local, nginx.local]

services:
  - crond
  - docker
  - fail2ban
  - systemd-timesyncd
