---
deps: [
  cronie,
  docker,
  fail2ban,
  git,
  python-docker,
  tmux,
  weechat
]

fail2ban_jails: [
  sshd.local,
  nginx.local
]

services:
  - cronie
  - docker
  - fail2ban
  - iptables
  - nginx
  - systemd-timesyncd
