---
- name: install pi-hole-server
  ansible.builtin.command: yay -S --noconfirm pi-hole-server
  args:
    creates: /bin/pihole

- name: install pi-hole-server dependencies
  become: true
  ansible.builtin.package:
    name: "{{ deps }}"
    state: present
