---
- name: restart_nginx
  become: true
  ansible.builtin.command: docker restart nginx

- name: restart firewalld
  become: true
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: restorecon nginx
  become: true
  ansible.builtin.command: restorecon -irv /etc/{{ item }}
  with_items:
    - nginx
    - letsencrypt
