---
- name: create the git daemon systemd service
  become: true
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
  loop:
    - git-daemon.service
  notify: start-gitdaemon
  tags: git, git-systemd
