---
- name: create letsencrypt shared root srv directory
  become: true
  ansible.builtin.file:
    path: /srv/http/letsencrypt
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0755
    state: directory
  tags:
    - ssl
    - https

- import_tasks: configuration-nginx-http.yml
- import_tasks: configuration-nginx-https.yml
- import_tasks: configuration-nginx-modsec.yml

- name: flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - http
    - modsec
    - modsec_rules
