---
- name: create awsddns server container
  become: true
  become_user: "{{ podman_user }}"
  diff: false
  containers.podman.podman_container:
    name: awsddns
    image: docker.io/bdebyl/awsddns:1.0.10
    recreate: false
    restart: true
    restart_policy: on-failure
    log_driver: journald
    env:
      AWS_ZONE_ID: "{{ aws_zone_id }}"
      AWS_ZONE_HOSTNAME: "{{ aws_zone_hostname }}"
      AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
      AWS_DEFAULT_REGION: "{{ aws_default_region }}"
  tags: ddns

- name: create systemd startup job for awsddns
  include_tasks: systemd-generate.yml
  vars:
    container_name: awsddns
  tags: ddns
