---
- name: create required drone volumes
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0755
  notify: restorecon podman
  loop:
    - "{{ drone_path }}/data"

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- import_tasks: podman/podman-check.yml
  vars:
    container_name: drone
    container_image: "{{ image }}"

- name: create drone-ci server container
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_container:
    name: drone
    image: "{{ image }}"
    restart_policy: on-failure:3
    log_driver: journald
    network:
      - shared
    env:
      DRONE_LOGS_DEBUG: "false"
      DRONE_RPC_DEBUG: "false"
      DRONE_GITHUB_CLIENT_ID: "{{ drone_gh_client_id }}"
      DRONE_GITHUB_CLIENT_SECRET: "{{ drone_gh_client_sec }}"
      DRONE_RPC_SECRET: "{{ drone_rpc_secret }}"
      DRONE_SERVER_HOST: "{{ ci_server_name }}"
      DRONE_SERVER_PROTO: "{{ drone_server_proto }}"
      DRONE_USER_FILTER: "{{ drone_user_filter }}"
    volumes:
      - "{{ drone_path }}/data:/data"
    ports:
      - "8080:80"

- name: create systemd startup job for drone
  include_tasks: podman/systemd-generate.yml
  vars:
    container_name: drone

- import_tasks: podman/podman-check.yml
  vars:
    container_name: drone-runner
    container_image: "{{ runner_image }}"

- name: create drone-ci worker container
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_container:
    name: drone-runner
    image: "{{ runner_image }}"
    restart_policy: on-failure:3
    log_driver: journald
    network:
      - shared
    env:
      DRONE_RPC_SECRET: "{{ drone_rpc_secret }}"
      DRONE_RPC_HOST: "drone"
      DRONE_RPC_PROTO: "{{ drone_runner_proto }}"
      DRONE_RUNNER_CAPACITY: "{{ drone_runner_capacity }}"
    volumes:
      - "/run/user/1002/podman/podman.sock:/var/run/docker.sock"
    ports:
      - "3000:3000"

- name: create systemd startup job for drone-runner
  include_tasks: podman/systemd-generate.yml
  vars:
    container_name: drone-runner
