---
- import_tasks: podman/podman-check.yml
  vars:
    container_name: awsddns
    container_image: "{{ image }}"

- name: create home.bdebyl.net awsddns server container
  become: true
  become_user: "{{ podman_user }}"
  diff: false
  containers.podman.podman_container:
    name: awsddns
    image: "{{ image }}"
    restart_policy: on-failure:3
    log_driver: journald
    env:
      AWS_ZONE_TTL: 60
      AWS_ZONE_ID: "{{ aws_zone_id }}"
      AWS_ZONE_HOSTNAME: "{{ aws_zone_hostname }}"
      AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
      AWS_DEFAULT_REGION: "{{ aws_default_region }}"

- name: create systemd startup job for awsddns
  include_tasks: podman/systemd-generate.yml
  vars:
    container_name: awsddns

- import_tasks: podman/podman-check.yml
  vars:
    container_name: awsddns-skudak
    container_image: "{{ image }}"

- name: create wiki.skudakrennsport.com awsddns server container
  become: true
  become_user: "{{ podman_user }}"
  diff: false
  containers.podman.podman_container:
    name: awsddns-skudak
    image: "{{ image }}"
    restart_policy: on-failure:3
    log_driver: journald
    env:
      AWS_ZONE_TTL: 60
      AWS_ZONE_ID: "{{ aws_skudak_zone_id }}"
      AWS_ZONE_HOSTNAME: "{{ aws_skudak_zone_hostname }}"
      AWS_ACCESS_KEY_ID: "{{ aws_skudak_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_skudak_secret_access_key }}"
      AWS_DEFAULT_REGION: "{{ aws_default_region }}"

- name: create systemd startup job for awsddns-skudak
  include_tasks: podman/systemd-generate.yml
  vars:
    container_name: awsddns-skudak
