---
- name: create sshpass_cron host directory volumes
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0755
  notify: restorecon podman
  loop:
    - "{{ sshpass_cron_path }}"
  tags: sshpass_cron

- name: copy sshpass_cron crontab
  become: true
  ansible.builtin.template:
    src: "files/sshpass_cron/{{ item }}"
    dest: "{{ sshpass_cron_path }}/{{ item }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0644
  loop:
    - crontab
  notify:
    - restorecon podman
  tags: sshpass_cron

- name: create sshpass_cron password file
  become: true
  ansible.builtin.copy:
    dest: "{{ sshpass_cron_path }}/unifi-pass"
    content: "{{ unifi_ssh_password }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0400
  notify:
    - restorecon podman
  tags: sshpass_cron

- name: flush handlers
  ansible.builtin.meta: flush_handlers
  tags: sshpass_cron

- name: create sshpass_cron container
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_container:
    name: sshpass_cron
    image: docker.io/bdebyl/sshpass-cron:1.0.9
    image_strict: true
    recreate: true
    restart: true
    restart_policy: on-failure:3
    log_driver: journald
    volumes:
      - "{{ sshpass_cron_path }}:/mnt"
  tags: sshpass_cron

- name: create systemd startup job for sshpass_cron
  include_tasks: systemd-generate.yml
  vars:
    container_name: sshpass_cron
  tags: sshpass_cron
