---
- name: set required podman firewall rules
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    zone: "public"
    state: enabled
  loop:
    - 53/tcp
    - 53/udp
    - 1153/tcp
    - 1153/udp
    - 80/tcp
    - 443/tcp
    - "{{ syslog_udp_default }}/udp"
    - "{{ syslog_udp_error }}/udp"
    - "{{ syslog_udp_unifi }}/udp"
  notify: restart firewalld
  tags: firewall
