---
- name: set required podman firewall rules
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp
    - "{{ syslog_udp_default }}/udp"
    - "{{ syslog_udp_error }}/udp"
    - "{{ syslog_udp_unifi }}/udp"
  notify: restart firewalld
  tags:
    - firewall
    - http
