---
- name: create systemd startup job for {{ container_name }}
  become: true
  become_user: "{{ podman_user }}"
  changed_when: false
  ansible.builtin.shell: |
    podman generate systemd --name {{ container_name }} > {{ podman_home }}/.config/systemd/user/{{ container_name }}.service
  tags: always

- name: enable systemd startup job for {{ container_name }}
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd:
    name: "{{ container_name }}.service"
    daemon_reload: true
    enabled: true
    state: restarted
    scope: user
  register: result
  retries: 3
  delay: 1
  until: result is not failed
  ignore_errors: true
  tags: always
