---
- name: create required partkeepr volumes
  community.general.docker_volume:
    name: "{{ item }}"
  with_items:
    - partkeepr-web-vol
    - partkeepr-conf-vol
    - partkeepr-data-vol
    - partkeepr-db-vol

- name: create partkeepr network
  community.general.docker_network:
    name: "partkeepr"

- name: create partkeepr-db container
  diff: false
  community.general.docker_container:
    name: partkeepr-db
    image: mariadb:10.0
    recreate: false
    restart: true
    restart_policy: on-failure
    restart_retries: 3
    networks:
      - name: "partkeepr"
    env:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: partkeepr
      MYSQL_USER: partkeepr
      MYSQL_PASSWORD: partkeepr
    volumes:
      - partkeepr-db-vol:/var/lib/mysql

- name: create partkeepr container
  diff: false
  community.general.docker_container:
    name: partkeepr
    image: mhubig/partkeepr:latest
    recreate: false
    restart: true
    restart_policy: on-failure
    restart_retries: 3
    networks:
      - name: "partkeepr"
    volumes:
      - partkeepr-db-conf-vol:/var/www/html/app/config
      - partkeepr-db-data-vol:/var/www/html/data
      - partkeepr-db-web-vol:/var/www/html/web

- name: create partkeepr-cron container
  diff: false
  community.general.docker_container:
    name: partkeepr-cron
    image: mhubig/partkeepr:latest
    entrypoint: []
    command: bash -c "crontab /etc/cron.d/partkeepr && cron -f"
    recreate: false
    restart: true
    restart_policy: on-failure
    restart_retries: 3
    volumes:
      - partkeepr-db-conf-vol:/var/www/html/app/config:ro
      - partkeepr-db-data-vol:/var/www/html/data
      - partkeepr-db-web-vol:/var/www/html/web

- name: create partkeepr container
  diff: false
  community.general.docker_container:
    name: partkeepr
    image: mhubig/partkeepr:latest
    recreate: false
    restart: true
    restart_policy: on-failure
    restart_retries: 3
    networks:
      - name: "partkeepr"
    ports:
      - "8081:80"
    volumes:
      - partkeepr-db-conf-vol:/var/www/html/app/config
      - partkeepr-db-data-vol:/var/www/html/data
      - partkeepr-db-web-vol:/var/www/html/web
